contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #nao channel"
    url: https://nfcore.slack.com/channels/nao
    about: Discussion about the nf-core/nao pipeline
